const tabela2025 = [
    // Ordem alfabética dos clubes da Série A 2025
    {
        nome: "Atlético Mineiro",
        sigla: "CAM",
        pontos: 0,
        vitorias: 0,
        empates: 0,
        derrotas: 0,
        golsMarcados: 0,
        golsSofridos: 0,
        saldoGols: 0,
    },
    {
        "nome": "Bahia",
        "sigla": "BAH",
        "pontos": 0,
        "vitorias": 0,
        "empates": 0,
        "derrotas": 0,
        "golsMarcados": 0,
        "golsSofridos": 0,
        "saldoGols": 0,
    },
    {
        nome: "Botafogo",
        sigla: "BOT",
        pontos: 0,
        vitorias: 0,
        empates: 0,
        derrotas: 0,
        golsMarcados: 0,
        golsSofridos: 0,
        saldoGols: 0,
    },
    {
        nome: "Ceará",
        sigla: "CEA",
        pontos: 0,
        vitorias: 0,
        empates: 0,
        derrotas: 0,
        golsMarcados: 0,
        golsSofridos: 0,
        saldoGols: 0,
    },
    {
        nome: "Corinthians",
        sigla: "COR",
        pontos: 0,
        vitorias: 0,
        empates: 0,
        derrotas: 0,
        golsMarcados: 0,
        golsSofridos: 0,
        saldoGols: 0,
    },
    {
        nome: "Cruzeiro",
        sigla: "CRU",
        pontos: 0,
        vitorias: 0,
        empates: 0,
        derrotas: 0,
        golsMarcados: 0,
        golsSofridos: 0,
        saldoGols: 0,
    },
    {
        nome: "Flamengo",
        sigla: "FLA",
        pontos: 0,
        vitorias: 0,
        empates: 0,
        derrotas: 0,
        golsMarcados: 0,
        golsSofridos: 0,
        saldoGols: 0,
    },
    {
        nome: "Fluminense",
        sigla: "FLU",
        pontos: 0,
        vitorias: 0,
        empates: 0,
        derrotas: 0,
        golsMarcados: 0,
        golsSofridos: 0,
        saldoGols: 0,
    },
    {
        nome: "Fortaleza",
        sigla: "FOR",
        pontos: 0,
        vitorias: 0,
        empates: 0,
        derrotas: 0,
        golsMarcados: 0,
        golsSofridos: 0,
        saldoGols: 0,
    },
    {
        nome: "Grêmio",
        sigla: "GRE",
        pontos: 0,
        vitorias: 0,
        empates: 0,
        derrotas: 0,
        golsMarcados: 0,
        golsSofridos: 0,
        saldoGols: 0,
    },
    {
        nome: "Internacional",
        sigla: "INT",
        pontos: 0,
        vitorias: 0,
        empates: 0,
        derrotas: 0,
        golsMarcados: 0,
        golsSofridos: 0,
        saldoGols: 0,
    },
    {
        nome: "Juventude",
        sigla: "JUV",
        pontos: 0,
        vitorias: 0,
        empates: 0,
        derrotas: 0,
        golsMarcados: 0,
        golsSofridos: 0,
        saldoGols: 0,
    },
    {
        nome: "Mirassol",
        sigla: "MIR",
        pontos: 0,
        vitorias: 0,
        empates: 0,
        derrotas: 0,
        golsMarcados: 0,
        golsSofridos: 0,
        saldoGols: 0,
    },
    {
        nome: "Palmeiras",
        sigla: "PAL",
        pontos: 0,
        vitorias: 0,
        empates: 0,
        derrotas: 0,
        golsMarcados: 0,
        golsSofridos: 0,
        saldoGols: 0,
    },
    {
        nome: "Red Bull Bragantino",
        sigla: "RBB",
        pontos: 0,
        vitorias: 0,
        empates: 0,
        derrotas: 0,
        golsMarcados: 0,
        golsSofridos: 0,
        saldoGols: 0,
    },
    {
        nome: "Santos",
        sigla: "SAN",
        pontos: 0,
        vitorias: 0,
        empates: 0,
        derrotas: 0,
        golsMarcados: 0,
        golsSofridos: 0,
        saldoGols: 0,
    },
    {
        nome: "São Paulo",
        sigla: "SAO",
        pontos: 0,
        vitorias: 0,
        empates: 0,
        derrotas: 0,
        golsMarcados: 0,
        golsSofridos: 0,
        saldoGols: 0,
    },
    {
        nome: "Sport",
        sigla: "SPT",
        pontos: 0,
        vitorias: 0,
        empates: 0,
        derrotas: 0,
        golsMarcados: 0,
        golsSofridos: 0,
        saldoGols: 0,
    },
    {
        nome: "Vasco da Gama",
        sigla: "VAS",
        pontos: 0,
        vitorias: 0,
        empates: 0,
        derrotas: 0,
        golsMarcados: 0,
        golsSofridos: 0,
        saldoGols: 0,
    },
    {
        nome: "Vitória",
        sigla: "VIT",
        pontos: 0,
        vitorias: 0,
        empates: 0,
        derrotas: 0,
        golsMarcados: 0,
        golsSofridos: 0,
        saldoGols: 0,
    },
];

export default tabela2025;